import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "../globals.css";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";

import NavContainer from "../components/NavContainer";
import { Footer } from "../components/Footer";

const poppins = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export async function generateStaticParams() {
  const locales = ["en", "ar"];
  return locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const { locale } = await (params as any);
  unstable_setRequestLocale(locale);

  const messages = await getMessages();
  console.log(locale);
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NavContainer />
        <div className=" pt-12 lg:pt-32">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
